export const chatStyles = {
  // ====== Mail icon ======
  mailIconAnchor: {
    position: 'absolute',
    right: 16,
    top: 0,
    display: 'flex',
    alignItems: 'center',
  },
  mailIconButton: {
    position: 'relative',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: 26,
    lineHeight: 1,
    padding: 4,
    borderRadius: 6,
  },
  unreadBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    padding: '0 5px',
    background: '#ef4444',
    color: '#fff',
    borderRadius: 9,
    fontSize: 11,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid #fff',
    boxSizing: 'content-box',
  },

  // ====== Title row ======
  titleRow: {
    position: 'relative',
    width: '100%',
    minHeight: 32,
  },

  // ====== ChatPanel ======
  chatPanel: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: 360,
    height: '100vh',
    background: '#ffffff',
    borderLeft: '1px solid #e5e7eb',
    boxShadow: '-4px 0 16px rgba(0,0,0,0.08)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    zIndex: 1000,
    animation: 'chatSlideIn 0.25s ease forwards',
  },
  chatPanelMobile: {
    position: 'fixed',
    inset: 0,
    width: '100%',
    height: '100%',
    borderRadius: 0,
    border: 'none',
    zIndex: 1000,
  },
  chatHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    background: '#f97316',
    color: '#fff',
    fontWeight: 700,
  },
  chatClose: {
    background: 'transparent',
    border: 'none',
    color: '#fff',
    fontSize: 20,
    lineHeight: 1,
    cursor: 'pointer',
    padding: 4,
  },

  // ====== History ======
  history: {
    flex: 1,
    overflowY: 'auto',
    padding: 12,
    background: '#fff7ed',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  msgRow: {
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '85%',
  },
  msgRowMine: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  msgRowOther: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  msgMeta: {
    fontSize: 10,
    color: '#9ca3af',
    marginBottom: 2,
  },
  msgBubble: {
    padding: '6px 10px',
    borderRadius: 12,
    background: '#ffffff',
    border: '1px solid #fed7aa',
    fontSize: 13,
    wordBreak: 'break-word',
    color: '#0f172a',
  },
  msgBubbleMine: {
    background: '#fb923c',
    color: '#ffffff',
    border: '1px solid #f97316',
  },
  msgSticker: {
    fontSize: 32,
    lineHeight: 1.2,
    padding: 0,
    background: 'transparent',
    border: 'none',
  },

  // ====== Input bar ======
  inputBar: {
    display: 'flex',
    flexDirection: 'column',
    borderTop: '1px solid #e5e7eb',
    background: '#ffffff',
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: 8,
  },
  textInput: {
    flex: 1,
    padding: '8px 10px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 13,
    outline: 'none',
  },
  iconButton: {
    background: 'transparent',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 18,
    padding: '4px 8px',
  },
  sendButton: {
    background: '#f97316',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 13,
  },
  sendButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },

  // ====== Sticker picker ======
  stickerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: 6,
    padding: 8,
    borderTop: '1px solid #e5e7eb',
    background: '#fafafa',
  },
  stickerCell: {
    fontSize: 24,
    background: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    padding: 4,
    cursor: 'pointer',
    lineHeight: 1,
  },

  // ====== Avatar popup ======
  popupAnchor: {
    position: 'relative',
    display: 'inline-flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  popupBubble: {
    position: 'absolute',
    bottom: 'calc(100% + 8px)',
    left: '50%',
    transform: 'translateX(-50%)',
    minWidth: 60,
    maxWidth: 180,
    padding: '6px 10px',
    borderRadius: 12,
    background: '#ffffff',
    border: '1px solid #f97316',
    fontSize: 13,
    color: '#0f172a',
    boxShadow: '0 4px 12px rgba(0,0,0,0.12)',
    wordBreak: 'break-word',
    textAlign: 'center',
    animation: 'popupFadeIn 0.2s ease forwards',
    zIndex: 5,
  },
  popupTail: {
    position: 'absolute',
    bottom: -6,
    left: '50%',
    transform: 'translateX(-50%) rotate(45deg)',
    width: 10,
    height: 10,
    background: '#ffffff',
    borderRight: '1px solid #f97316',
    borderBottom: '1px solid #f97316',
  },
  popupSticker: {
    position: 'absolute',
    top: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 72,
    height: 72,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 56,
    pointerEvents: 'none',
    animation: 'popupFadeIn 0.2s ease forwards',
    zIndex: 5,
  },

  error: {
    color: '#dc2626',
    fontSize: 12,
    padding: '0 12px 8px',
  },
}
